### PR TITLE
Feature/mark infix

### PR DESCRIPTION
**Pull request by marklnichols**
Added support for infix functions and operators

### CODE REVIEW

**Comment by marklnichols** [comment]
I'm going to let you take a look at Variables.hs and Record.hs -- I've put them back to their original state.  The hlint suggestions do not compile.

**Comment by ndmitchell** [comment]
I've just tweaked HLint to be less violent and am releasing a new version now. In a few hours it should work once more.

**Comment by marklnichols** [comment]
Ok, is there a way to get it to try again or do I just need to do a dummy PR?

**Comment by marklnichols** [comment]
I just re-merged -- it seemed to think it needed merging, though nothing had changed -- It might have been due to some offending trailing spaces, I just realized my "trim trailing spaces" was turned off.

**Comment by marklnichols** [comment]
I don't know why the Travis build is failing.  I haven't found anything that seems to relate to my code.  There are a lot of instances of things like:
"Unable to connect..."
"Failed to fetch..."
"E: Unable to locate package ghc-head"
But I don't know what the real culprit is.

**Comment by ndmitchell** [comment]
Thanks!

**Comment by ndmitchell** [comment]
For info, the travis rules change over time - e.g. when a new HLint is released, or when I update the script in https://github.com/ndmitchell/neil. Generally just rebuild the master branch, if that fails, tell me to fix it and you can merge in my changes.

**Pull request merged**
